name: Check Markdown links

on: push

jobs:
#  markdown-link-check:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@main
#    - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#name: ci
#jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JustinBeckwith/linkinator-action@v1
